apiVersion: v1
kind: Pod
metadata:
  name: kube
  labels:
    app: kube
    svc: kube-svc
spec:
  containers:
    - image: docker.io/udigeri/kube
      name: kube
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 150Mi
          cpu: 10m
        limits:
          memory: 300Mi
          cpu: 30m
